apiVersion: v1
kind: Secret
metadata:
  name: heketi-admin
  namespace: default
data:
  # base64 encoded password. E.g.: echo -n "password" | base64
  key: Tm92ZW1iZXJTaWx2ZXJBc3Ryb25hdXQ0Mzky
type: kubernetes.io/glusterfs

---
apiVersion: v1
kind: Secret
metadata:
  name: heketi-user
  namespace: default
data:
  # base64 encoded password. E.g.: echo -n "password" | base64
  key: TGVtb25hZGVSb29mU2VuYXRlNTQ0Mw==
type: kubernetes.io/glusterfs
